### ISSUE TITLE
Multiple table in 1 page

### ISSUE THREAD

**Issue by khun84** [ropensci/tabulizerjars#1]
Is there param that I can parse in to extract **more than 1 table per page**? 

I have a pdf page with 2 tables:
- table 1 is 2 columns and multiple rows
- **table 2 has 2 columns and multiple rows, but some of the cells are merged)**. 

I use the `extract_table` function with default param and the output only has 1 table (table 1).

What I can think of is to set  `method =  'asis'` but I do not know to proceed with the output java object. Is there any documentation I can refer to?

**Comment by leeper** [comment]
I've moved this here: https://github.com/ropenscilabs/tabulizer/issues/22
