### ISSUE TITLE
Switch to PDFBox 2.0

### ISSUE THREAD

**Issue by leeper** [ropensci/tabulizerjars#3]
This may require downstream changes in tabulizer. No need to do anything until https://github.com/tabulapdf/tabula-java/issues/52 happens.

**Comment by jazzido** [comment]
Hey @leeper — We closed tabulapdf/tabula-java#52 a few days ago. It's not yet released as a jar; that will happen in the coming days.

I'm happy to help adapting tabulizer to our changes.

**Comment by leeper** [comment]
@jazzido great, I'll hopefully have time Thursday and Friday to make a full assessment of what needs updating.
